name: CI
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: set up env
        run: |
          python -m pip install -r requirements.txt

      # Execute unit tests
      - name: test
        run: python -m unittest
