experiment:
    id: maskrcnn_leaves
    seed: 1324

checkpoint: 'out/checkpoints'
tensorboard: 'run'

##Data
data:
    train: 'data/train'
    val: 'data/val'

##Training
train:
    n_gpus: 1
    workers: 4
    max_epoch: 200
    batch_size: 8
    n_classes: 2
    overfit: False
    lr: 0.0001

val:
    nms_th: 0.5
    prob_th: 0.6
