experiment:
    id: maskrcnn_leaves
    seed: 1324

checkpoint: 'out/checkpoints'
tensorboard: 'run'

##Data
data:
    train: 
      - 'data/train'
      - 'data/plant_phenotype'
    val: 'data/val'

##Training
train:
    n_gpus: 1
    workers: 12
    max_epoch: 200
    batch_size: 4
    n_classes: 2
    overfit: False
    lr: 0.0005

val:
    nms_th: 0.5
    prob_th: 0.6
