runtime:
  all_reduce_alg: null
  batchnorm_spatial_persistent: false
  dataset_num_private_threads: null
  default_shard_dim: -1
  distribution_strategy: mirrored
  enable_xla: false
  gpu_thread_mode: null
  loss_scale: null
  mixed_precision_dtype: null
  num_cores_per_replica: 1
  num_gpus: 0
  num_packs: 1
  per_gpu_thread_count: 0
  run_eagerly: false
  task_index: -1
  tpu: null
  tpu_enable_xla_dynamic_padder: null
  use_tpu_mp_strategy: false
  worker_hosts: null
task:
  allow_image_summary: false
  annotation_file: null
  differential_privacy_config: null
  export_config:
    cast_detection_classes_to_float: false
    cast_num_detections_to_float: false
    output_intermediate_features: false
    output_normalized_coordinates: false
  freeze_backbone: false
  init_checkpoint: null
  init_checkpoint_module: null
  init_checkpoint_modules: backbone
  losses:
    box_loss_weight: 50
    focal_loss_alpha: 0.25
    focal_loss_gamma: 1.5
    huber_loss_delta: 0.1
    l2_weight_decay: 0.0001
    loss_weight: 1.0
  max_num_eval_detections: 100
  model:
    anchor:
      anchor_size: 4.0
      aspect_ratios: [0.5, 1.0, 2.0]
      num_scales: 3
    backbone:
      resnet:
        bn_trainable: true
        depth_multiplier: 1.0
        model_id: 50
        replace_stem_max_pool: false
        resnetd_shortcut: false
        scale_stem: true
        se_ratio: 0.0
        stem_type: v0
        stochastic_depth_drop_rate: 0.0
      type: resnet
    decoder:
      fpn:
        fusion_type: sum
        num_filters: 256
        use_keras_layer: false
        use_separable_conv: false
      type: fpn
    detection_generator:
      apply_nms: true
      box_coder_weights: null
      max_num_detections: 100
      nms_iou_threshold: 0.5
      nms_version: v2
      pre_nms_score_threshold: 0.05
      pre_nms_top_k: 5000
      return_decoded: null
      soft_nms_sigma: null
      tflite_post_processing:
        detections_per_class: 5
        h_scale: 1.0
        max_classes_per_detection: 5
        max_detections: 200
        nms_iou_threshold: 0.5
        nms_score_threshold: 0.1
        normalize_anchor_coordinates: false
        omit_nms: false
        use_regular_nms: false
        w_scale: 1.0
        x_scale: 1.0
        y_scale: 1.0
      use_class_agnostic_nms: false
      use_cpu_nms: false
    head:
      attribute_heads: []
      num_convs: 4
      num_filters: 256
      share_classification_heads: false
      share_level_convs: true
      use_separable_conv: false
    input_size: [640, 640, 3]
    max_level: 7
    min_level: 3
    norm_activation:
      activation: relu
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: false
    num_classes: 2
  name: null
  per_category_metrics: false
  train_data:
    apply_tf_data_service_before_batching: false
    autotune_algorithm: null
    block_length: 1
    cache: false
    cycle_length: null
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: true
    dtype: bfloat16
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 8
    input_path: /home/stefan.steinheber/tensorflow_datasets/leaf_instance_dataset/1.0.0/*train*
    is_training: true
    parser:
      aug_policy: null
      aug_rand_hflip: true
      aug_scale_max: 1.2
      aug_scale_min: 0.8
      aug_type: null
      keep_aspect_ratio: true
      match_threshold: 0.5
      max_num_instances: 100
      num_channels: 3
      pad: true
      skip_crowd_during_training: true
      unmatched_threshold: 0.5
    prefetch_buffer_size: null
    ram_budget: null
    seed: null
    sharding: true
    shuffle_buffer_size: 10000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: ''
    trainer_id: null
    weights: null
  use_coco_metrics: false
  use_wod_metrics: false
  validation_data:
    apply_tf_data_service_before_batching: false
    autotune_algorithm: null
    block_length: 1
    cache: false
    cycle_length: null
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: true
    dtype: bfloat16
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 8
    input_path: /home/stefan.steinheber/tensorflow_datasets/leaf_instance_dataset/1.0.0/*val*
    is_training: false
    parser:
      aug_policy: null
      aug_rand_hflip: false
      aug_scale_max: 1.0
      aug_scale_min: 1.0
      aug_type: null
      keep_aspect_ratio: true
      match_threshold: 0.5
      max_num_instances: 100
      num_channels: 3
      pad: true
      skip_crowd_during_training: true
      unmatched_threshold: 0.5
    prefetch_buffer_size: null
    ram_budget: null
    seed: null
    sharding: true
    shuffle_buffer_size: 10000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: ''
    trainer_id: null
    weights: null
trainer:
  allow_tpu_summary: false
  best_checkpoint_eval_metric: ''
  best_checkpoint_export_subdir: ''
  best_checkpoint_metric_comp: higher
  checkpoint_interval: 1000
  continuous_eval_timeout: 3600
  eval_tf_function: true
  eval_tf_while_loop: false
  loss_upper_bound: 1000000.0
  max_to_keep: 3
  optimizer_config:
    ema: null
    learning_rate:
      stepwise:
        boundaries: [15000, 20000]
        name: PiecewiseConstantDecay
        offset: 0
        values: [0.12, 0.012, 0.0012]
      type: stepwise
    optimizer:
      sgd:
        clipnorm: null
        clipvalue: null
        decay: 0.0
        global_clipnorm: null
        momentum: 0.9
        name: SGD
        nesterov: false
      type: sgd
    warmup:
      linear:
        name: linear
        warmup_learning_rate: 0.0067
        warmup_steps: 500
      type: linear
  preemption_on_demand_checkpoint: true
  recovery_begin_steps: 0
  recovery_max_trials: 0
  steps_per_loop: 1000
  summary_interval: 1000
  train_steps: 584200
  train_tf_function: true
  train_tf_while_loop: true
  validation_interval: 1000
  validation_steps: 278
  validation_summary_subdir: validation
